import type { EquationPreset } from '../types';

export const EQUATION_PRESETS: EquationPreset[] = [
    { name: 'Sine Wave', equation: 'a * sin(b * x + t)', category: 'classic' },
    { name: 'Wavy Tan', equation: 'a * cos(b*x + t)/tan(x)', category: 'classic' },
    { name: 'Interference', equation: 'a * (sin(b*x+t) + cos(c*x*0.5))', category: 'classic' },
    { name: 'Damped Cosine', equation: 'a * exp(-b*abs(x)) * cos(c*x - t)', category: 'classic' },
    { name: 'Gaussian Pulses', equation: 'a * exp(-pow((x*b - sin(t)) * c, 2))', category: 'classic' },
    { name: 'Chirp Pulse', equation: 'a * sin(pow(x*b, 2) + t)', category: 'classic' },
    { name: 'Bessel-like', equation: 'a * cos(sqrt(x*x + b*b) - t)', category: 'classic' },
    { name: 'Gated Sine', equation: 'a * (floor(b*x+t) % 2 ? 1 : -1) * sin(c*x)', category: 'classic' },
    { name: 'Square Wave', equation: 'floor(b*x+t) % 2 == 0 ? a : -a', category: 'classic' },
    { name: 'Rectifier Pulse', equation: 'a * (sin(b*x*t*2) > 0.8 ? 1 : 0)', category: 'classic' },
    { name: 'Fractal Noise', equation: 'a * (random() > sin(b*x+t) ? 1 : -1)', category: 'classic' },
    { name: 'Gated Noise', equation: 'a * sin(b*x+t) * (random() > 0.5 ? 1 : -1)', category: 'classic'},
    { name: 'Complex Steps', equation: 'a * floor(sin(t)*5*x) / 5', category: 'classic' },
    { name: 'Moving Sigmoid', equation: 'a * (1 / (1 + exp(-b * (x - sin(t)))))', category: 'classic' },
    { name: 'Parabola', equation: 'a * x^2', category: 'classic' },
    { name: 'Hyperbola', equation: 'a / x', category: 'classic' },
    // Modified Presets
    { name: 'Simple Sine Wave', equation: 'sin(x + t)', category: 'modified' },
    { name: 'Interference Sinus Pattern', equation: 'sin(x*a + t) + sin(x*b - t)', category: 'modified' },
    { name: 'Standing Wave', equation: 'sin(a*x) * cos(b*t)', category: 'modified' },
    { name: 'Complex Amplitude', equation: 'a * sin(b*x-t) * cos(c*x+t)', category: 'modified' },
    { name: 'Damped Oscillator', equation: 'exp(-t*0.2) * sin(x*a + t*b)', category: 'modified' },
    { name: 'Moving Wave Packet', equation: 'exp(-pow(x - t, 2)) * cos(x * 5)', category: 'modified' },
    { name: 'Chirped Pulse Mod', equation: 'cos(pow(x + t, 2))', category: 'modified' },
    { name: 'Soliton-like Wave', equation: '1 / cosh(x - c*t)', category: 'modified' },
    { name: 'Bessel Function (J0 approx.)', equation: '(1 - pow(x/2,2) + pow(x/2,4)/4 - pow(x/2,6)/36) * cos(t)', category: 'modified' },
    { name: 'Gaussian Pulses Mod', equation: 'exp(-pow(x*a-sin(t),2)) + exp(-pow(x*b+cos(t),2))', category: 'modified' },
    { name: 'Moving Sigmoid Mod', equation: '1 / (1 + exp(-(x*a - t)))', category: 'modified' },
    { name: 'Gated Noise Mod', equation: '(sin(x*a+t)>0.5?1:0) * random()', category: 'modified' },
    { name: 'Rectifier Pulse Mod', equation: 'max(0, sin(a*x-t) - 0.8) * 5', category: 'modified' },
    { name: 'Wavy Tan Mod', equation: 'tan(x*a)*sin(t*b)*0.1', category: 'modified' },
    // New Hyperbolic, Inverse, & Utility Functions
    { name: 'Tanh Step Function', equation: 'a * tanh(b * (x - cos(t)))', category: 'modified' },
    { name: 'Inverse Sine Wave', equation: 'a * asin(sin(b * x + t))', category: 'modified' },
    { name: 'Hyperbolic Spiral', equation: 'a * sinh(x * 0.1) * cos(t * b)', category: 'modified' },
    { name: 'Sign Square Wave', equation: 'a * sign(sin(b * x + t) - 0.5)', category: 'modified' },
    { name: 'Stepped Quantizer', equation: 'a * round(b * sin(c * x * cos(t))) / b', category: 'modified' },
    { name: 'Chaotic Inverse Tan', equation: 'a * atan(sin(x*b) / (cos(t*c)+0.1))', category: 'modified' },
];